{
  lib,
  pkgs,
  config,
  ...
}:

{
  options.system = {
    username = lib.mkOption {
      type = lib.types.str;
      default = "nusk";
    };
    userFullname = lib.mkOption {
      type = lib.types.str;
      default = "Nusk Rbb";
    };
    userEmail = lib.mkOption {
      type = lib.types.str;
      default = "nuskrbb1741dn@gmail.com";
    };
    homeDir = lib.mkOption {
      type = lib.types.str;
      default =
        if pkgs.stdenv.isDarwin then
          "/Users/${config.system.username}"
        else
          "/home/${config.system.username}";
    };
    dotfilesDir = lib.mkOption {
      type = lib.types.str;
      default = "${config.system.homeDir}/.dotfiles";
    };
    workspaceDir = lib.mkOption {
      type = lib.types.str;
      default = "${config.system.homeDir}/workspace";
    };
    initialHashedPassword = lib.mkOption {
      type = lib.types.str;
      # Generated by: mkpasswd -m scrypt
      default = "$7$CU..../....ndusC6cBcgdi8KIaV4gMX/$R.WlzH0EZS8IcuEqHGb7vmDvlrceAu/aJ1tJPwVdSd9";
    };

    xdg = lib.mkOption {
      type = lib.types.submodule {
        options = {
          configDir = lib.mkOption {
            type = lib.types.str;
            default = ".config";
          };

          dataDir = lib.mkOption {
            type = lib.types.str;
            default = ".local/share";
          };

          cacheDir = lib.mkOption {
            type = lib.types.str;
            default = ".cache";
          };

          stateDir = lib.mkOption {
            type = lib.types.str;
            default = ".local/state";
          };

          configHome = lib.mkOption {
            type = lib.types.str;
            default = "${config.system.homeDir}/${config.system.xdg.configDir}";
          };

          dataHome = lib.mkOption {
            type = lib.types.str;
            default = "${config.system.homeDir}/${config.system.xdg.dataDir}";
          };

          cacheHome = lib.mkOption {
            type = lib.types.str;
            default = "${config.system.homeDir}/${config.system.xdg.cacheDir}";
          };

          stateHome = lib.mkOption {
            type = lib.types.str;
            default = "${config.system.homeDir}/${config.system.xdg.stateDir}";
          };
        };
      };
      default = { };
    };

    zshDotDir = lib.mkOption {
      type = lib.types.str;
      default = "${config.system.xdg.configHome}/fish";
    };
  };
}
